// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').controller('interviewManager', [
    '$scope', 'sectionsMgr', function($scope, sectionsMgr) {
      var InterviewManagerSection;
      InterviewManagerSection = (function() {
        function InterviewManagerSection() {
          console.log($scope);
          console.log('interview manager section created');
          this.section = {
            title: 'Interview Manager'
          };
          sectionsMgr.setCurrentSection(this.section);
          $scope.$on('$destroy', (function(_this) {
            return function() {
              console.log('InterviewManager destroyed');
              return sectionsMgr.setCurrentSection(null);
            };
          })(this));
        }

        return InterviewManagerSection;

      })();
      return new InterviewManagerSection();
    }
  ]);

}).call(this);

//# sourceMappingURL=interviewManager.js.map
