// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('dannyThibaudeauApp').controller('nyxLib', [
    '$scope', '$route', '$location', 'sectionsMgr', function($scope, $route, $location, sectionsMgr) {
      var NyxLibSection;
      NyxLibSection = (function() {
        function NyxLibSection() {
          console.log($scope);
          console.log('nyxLib manager section created');
          $scope.nyxdocUrl = 'http://' + $location.host() + ':' + $location.port() + '/nyxdoc';
          this.section = {
            title: 'Nyx Libraries'
          };
          sectionsMgr.setCurrentSection(this.section);
          $scope.$on('$destroy', (function(_this) {
            return function() {
              console.log('nyxLib destroyed');
              return sectionsMgr.setCurrentSection(null);
            };
          })(this));
        }

        return NyxLibSection;

      })();
      return new NyxLibSection();
    }
  ]);

}).call(this);

//# sourceMappingURL=nyxLib.js.map
