// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').controller('nyxLib', [
    '$scope', '$route', '$location', 'sectionsMgr', function($scope, $route, $location, sectionsMgr) {
      var InterviewManagerSection;
      InterviewManagerSection = (function() {
        function InterviewManagerSection() {
          console.log($scope);
          console.log('nyxLib manager section created');
          this.section = {
            title: 'Nyx Libraries'
          };
          sectionsMgr.setCurrentSection(this.section);
          $scope.$on('$destroy', (function(_this) {
            return function() {
              console.log('nyxLib destroyed');
              return sectionsMgr.setCurrentSection(null);
            };
          })(this));
        }

        return InterviewManagerSection;

      })();
      return new InterviewManagerSection();
    }
  ]);

}).call(this);

//# sourceMappingURL=nyxLib.js.map
