// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').factory('sectionsMgr', [
    '$route', '$location', function($route, $location) {
      var ActiveSection;
      ActiveSection = (function() {
        function ActiveSection() {}

        ActiveSection.prototype.setCurrentSection = function(section) {
          return this._currentSection = section;
        };

        ActiveSection.prototype.getCurrentSection = function() {
          return this._currentSection;
        };

        return ActiveSection;

      })();
      return new ActiveSection();
    }
  ]);

}).call(this);

//# sourceMappingURL=sectionsMgr.js.map
