// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('dannyThibaudeauApp').factory('sectionsMgr', [
    '$route', '$location', function($route, $location) {
      var ActiveSection;
      ActiveSection = (function() {
        function ActiveSection() {
          this._events = {
            sectionActivated: [],
            sectionDeactivated: []
          };
        }

        ActiveSection.prototype.setCurrentSection = function(section) {
          this._currentSection = section;
          return this._events.sectionActivated.forEach(function(fct) {
            return fct(section);
          });
        };

        ActiveSection.prototype.getCurrentSection = function() {
          return this._currentSection;
        };

        ActiveSection.prototype.on = function(eventId, fct) {
          return this._events[eventId].push(fct);
        };

        return ActiveSection;

      })();
      return new ActiveSection();
    }
  ]);

}).call(this);

//# sourceMappingURL=sectionsMgr.js.map
