// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var args, file, params, paramsStr;
    args = {};
    paramsStr = window.location.href.slice(window.location.href.indexOf('?') + 1);
    if (paramsStr != null) {
      params = paramsStr.split('&');
      params.forEach(function(p) {
        var parts;
        parts = p.split('=');
        return args[parts[0]] = parts[1];
      });
    }
    if (args.file != null) {
      file = args.file.replace('.', '/');
      return $.get("http://www.cds.essai.danny-thibaudeau.ca/services/file/" + file, function(data) {
        $("#code").text(data);
        return SyntaxHighlighter.highlight($("#code"));
      });
    }
  });

}).call(this);

//# sourceMappingURL=main.js.map
