// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('globalHeader', [
    '$location', '$route', '$routeParams', function($location, $route, $routeParams) {
      return {
        restrict: 'EA',
        scope: true,
        templateUrl: 'directives/globalHeader.html',
        link: function($scope, $element, $attr) {
          var GlobalHeader;
          GlobalHeader = (function() {
            function GlobalHeader() {
              $scope.$on('$routeChangeSuccess', function() {
                return $scope.originalPath = $route.current.originalPath;
              });
              $scope.originalPath = $route.current.originalPath;
              $scope.goHome = (function(_this) {
                return function() {
                  console.log('going home');
                  $location.path('/');
                };
              })(this);
            }

            return GlobalHeader;

          })();
          return new GlobalHeader();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=globalHeader.js.map
