// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('globalMenu', [
    '$route', '$routeParams', function($route, $routeParams) {
      return {
        restrict: 'EA',
        scope: true,
        templateUrl: 'directives/globalMenu.html',
        link: function(scope, element, attributes) {
          console.log(attributes);
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=globalMenu.js.map
