// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('globalMenuItem', [
    '$location', '$route', '$routeParams', function($location, $route, $routeParams) {
      return {
        restrict: 'EA',
        scope: true,
        templateUrl: 'directives/globalMenuItem.html',
        link: function($scope, $element, $attr) {
          var GlobalMenuItem;
          GlobalMenuItem = (function() {
            function GlobalMenuItem() {
              this.text = $attr.text;
              this.updateItemStatus($route.current.originalPath);
              $scope.text = this.text;
              console.log($attr);
              $scope.$on('$routeChangeSuccess', (function(_this) {
                return function() {
                  return _this.updateItemStatus($route.current.originalPath);
                };
              })(this));
              $scope.changeRoute = (function(_this) {
                return function() {
                  return $location.path($attr.route);
                };
              })(this);
            }

            GlobalMenuItem.prototype.updateItemStatus = function(currentRoute) {
              if (currentRoute === $attr.route) {
                return $element.addClass('menu-item-selected');
              } else {
                return $element.removeClass('menu-item-selected');
              }
            };

            return GlobalMenuItem;

          })();
          return new GlobalMenuItem();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=globalMenuItem.js.map
