// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('globalHeader', function() {
    return {
      restrict: 'E',
      templateUrl: 'directives/globalHeader.html',
      link: function() {
        var test;
        return test = "test";
      }
    };
  });

}).call(this);

//# sourceMappingURL=globalHeader.js.map
