// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('pagesControl', [
    function() {
      return {
        restrict: 'EA',
        scope: true,
        templateUrl: 'directives/pagesControl.html',
        controller: function($scope) {
          var PageControl;
          PageControl = (function() {
            function PageControl() {
              this._items = [];
              console.log('page control created');
              console.log($scope.$parent.pages);
              if ($scope.$parent.pages != null) {
                this._items = $scope.$parent.pages;
              }
            }

            PageControl.prototype.getItems = function() {
              return this._items;
            };

            return PageControl;

          })();
          return new PageControl();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=pagesControl.js.map
