// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('pagesControl', [
    '$compile', function($compile) {
      return {
        restrict: 'EA',
        scope: true,
        templateUrl: 'directives/pagesControl.html',
        controller: function($scope) {
          var PageControl;
          PageControl = (function() {
            function PageControl() {
              console.log('page control created');
              console.log($scope.$parent.pages);
              this.setActivePage(0);
              if ($scope.$parent.pages != null) {
                $scope.pages = $scope.$parent.pages;
              }
            }

            PageControl.prototype.setActivePage = function(index) {
              return $scope.activePage = $scope.pages[index];
            };

            return PageControl;

          })();
          return new PageControl();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=pagesControl.js.map
