// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('pagesControl', function() {
    return {
      restrict: '',
      scope: true,
      transclude: true,
      templateUrl: 'directives/pagesControl.html',
      controller: function($scope) {
        var PageControl;
        PageControl = (function() {
          function PageControl() {
            console.log('page control created');
            this._items = [
              {
                title: 'Overview',
                href: 'overview',
                selHandler: (function(_this) {
                  return function() {
                    return {};
                  };
                })(this)
              }, {
                title: 'Technologies',
                href: 'technologies',
                selHandler: (function(_this) {
                  return function() {
                    return {};
                  };
                })(this)
              }, {
                title: 'Download',
                href: 'download',
                selHandler: (function(_this) {
                  return function() {
                    return {};
                  };
                })(this)
              }
            ];
          }

          PageControl.prototype.getItems = function() {
            return this._items;
          };

          return PageControl;

        })();
        return new PageControl();
      }
    };
  });

}).call(this);

//# sourceMappingURL=pagesControl.js.map
