// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('porteFolioItem', [
    '$compile', function($compile) {
      return {
        scope: true,
        restrict: 'EA',
        templateUrl: 'directives/porteFolioItem.html',
        link: function($scope, $element, $attr) {
          var PorteFolioItem;
          PorteFolioItem = (function() {
            function PorteFolioItem() {
              var desc, descElem;
              this.title = $attr.title;
              this.height = 400;
              $scope.title = this.title;
              $scope.img = $attr.img;
              $scope.updateLayout = (function(_this) {
                return function() {
                  return _this.updateLayout();
                };
              })(this);
              $scope.descStyle = (function(_this) {
                return function() {
                  return _this.descStyle();
                };
              })(this);
              descElem = $element.find('.porte-folio-item-description');
              desc = $compile("<ng-include onload=\"updateLayout()\" src=\"" + $attr.description + "\"></ng-include>")($scope);
              descElem.append(desc);
            }

            PorteFolioItem.prototype.updateLayout = function() {
              var descDiv, descHeight, img, imgDiv, imgHeight;
              imgDiv = $element.find('.porte-folio-item-image');
              img = imgDiv.find('img');
              descDiv = $element.find('.porte-folio-item-description');
              imgHeight = img.height();
              descHeight = descDiv.height();
              this.height = Math.max(img.height(), descDiv.height());
              console.log("imgHeight : " + imgHeight + " -- descHeight : " + descHeight);
              return console.log("height : " + this.height);
            };

            PorteFolioItem.prototype.descStyle = function() {
              return {
                height: "200px"
              };
            };

            return PorteFolioItem;

          })();
          return new PorteFolioItem();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=porteFolioItem.js.map
