// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('sectionMenu', [
    'sectionsMgr', '$routeParams', function(sectionsMgr, $routeParams) {
      return {
        scope: true,
        restrict: 'EA',
        templateUrl: 'directives/sectionMenu.html',
        link: function($scope, $element, $attr) {
          var SectionMenu;
          SectionMenu = (function() {
            function SectionMenu() {
              this._section = null;
              console.log('route params');
              console.log($routeParams);
              $scope.getClassName = (function(_this) {
                return function() {
                  return _this.getClassName();
                };
              })(this);
              $scope.isVisible = (function(_this) {
                return function(index) {
                  return $scope.selectedItem === index;
                };
              })(this);
              $scope.selectItem = (function(_this) {
                return function(index) {
                  $scope.selectedItem = index;
                  return $scope.menuItems[index].selHandler();
                };
              })(this);
              $scope.menuItems = [];
              $scope.selectedItem = 0;
              sectionsMgr.on('sectionActivated', (function(_this) {
                return function(section) {
                  if (section != null) {
                    $scope.menuItems = section.menu;
                    _this._section = section;
                    if ($routeParams.idx != null) {
                      return $scope.selectedItem = parseInt($routeParams.idx);
                    } else {
                      return $scope.selectedItem = 0;
                    }
                  } else {
                    _this.section = null;
                    return $scope.menuItems = [];
                  }
                };
              })(this));
            }

            SectionMenu.prototype.getClassName = function() {
              var className;
              className = "section-menu-default";
              if (($scope.menuItems != null) && $scope.menuItems.length > 0) {
                className = "section-menu-visible";
              }
              return className;
            };

            return SectionMenu;

          })();
          return new SectionMenu();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=sectionMenu.js.map
