// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('downloads', [
    function() {
      return {
        restrict: 'EA',
        scope: {},
        templateUrl: 'directives/downloads.html',
        link: function($scope, $element, $attr) {
          var Downloads;
          Downloads = (function() {
            function Downloads() {
              $.get("http://www.cds.porte-folio.danny-thibaudeau.ca/Services/ResInfo/" + $attr.item + "/" + $attr.platform).then((function(_this) {
                return function(data) {
                  console.log(data);
                  $scope.items = data.files;
                  return $scope.items.forEach(function(item) {
                    item.platform = $attr.platform;
                    return item.href = "http://www.cds.porte-folio.danny-thibaudeau.ca/Resources/" + item.file;
                  });
                };
              })(this));
            }

            return Downloads;

          })();
          return new Downloads();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=downloads.js.map
