// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').directive('pagesContainer', [
    '$compile', function($compile) {
      return {
        require: '^pages-control',
        restrict: 'EA',
        scope: false,
        templateUrl: 'directives/pagesContainer.html',
        link: function($scope, $element, $attr) {
          var PagesContainer;
          PagesContainer = (function() {
            function PagesContainer() {
              var root;
              console.log('pages container created');
              console.log($scope.$parent.activePage);
              root = $element.find('.pages-root');
              $scope.$parent.pages.forEach((function(_this) {
                return function(page) {
                  var childScope, pageElement;
                  childScope = $scope.$new();
                  childScope.page = page;
                  pageElement = $compile("<div page></div>")(childScope);
                  return root.append(pageElement);
                };
              })(this));
            }

            return PagesContainer;

          })();
          return new PagesContainer();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=pagesContainer.js.map
