// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('dannyThibaudeauApp').directive('porteFolioItem', [
    '$compile', '$window', '$location', 'sectionsMgr', function($compile, $window, $location, sectionsMgr) {
      return {
        scope: true,
        restrict: 'EA',
        templateUrl: 'directives/porteFolioItem.html',
        link: function($scope, $element, $attr) {
          var PorteFolioItem;
          PorteFolioItem = (function() {
            function PorteFolioItem() {
              var desc, descElem;
              this.title = $attr.title;
              this.height = null;
              this.width = null;
              this.sectionId = $attr.sectionId;
              $scope.title = this.title;
              $scope.img = $attr.img;
              $scope.href = $attr.href;
              $scope.updateLayout = (function(_this) {
                return function() {
                  return _this.updateLayout();
                };
              })(this);
              $scope.descStyle = (function(_this) {
                return function() {
                  return _this.descStyle();
                };
              })(this);
              $scope.bkgndImage = (function(_this) {
                return function() {
                  return _this.bkgndImage();
                };
              })(this);
              $scope.onTitleClicked = (function(_this) {
                return function() {
                  return _this.onTitleClicked();
                };
              })(this);
              angular.element($window).bind('resize', (function(_this) {
                return function() {
                  _this.updateLayout();
                  return $scope.$apply();
                };
              })(this));
              descElem = $element.find('.porte-folio-item-description');
              desc = $compile("<ng-include onload=\"updateLayout()\" src=\"" + $attr.description + "\"></ng-include>")($scope);
              descElem.append(desc);
            }

            PorteFolioItem.prototype.updateLayout = function() {
              var descDiv, descHeight, imgDiv, width;
              imgDiv = $element.find('.porte-folio-item-image');
              descDiv = $element.find('.porte-folio-item-description');
              descHeight = descDiv.height();
              width = $element.width() - imgDiv.outerWidth(true) - 100;
              if (width !== this.width) {
                this.width = width;
                setTimeout((function(_this) {
                  return function() {
                    _this.updateLayout();
                    return $scope.$apply();
                  };
                })(this), 100);
              }
              return this.height = descHeight;
            };

            PorteFolioItem.prototype.descStyle = function() {
              var style;
              if (this.height && this.width) {
                style = {
                  'width': this.width + 'px'
                };
              }
              return style;
            };

            PorteFolioItem.prototype.bkgndImage = function() {
              var style;
              style = {
                'background-image': "url('" + $attr.img + "')"
              };
              if (this.height) {
                style['height'] = this.height + 'px';
              }
              return style;
            };

            PorteFolioItem.prototype.onTitleClicked = function() {
              return $location.path($scope.href);
            };

            return PorteFolioItem;

          })();
          return new PorteFolioItem();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=porteFolioItem.js.map
