// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('dannyThibaudeauApp').controller('Porte-folio', [
    '$route', function($route) {
      return console.log($route);
    }
  ]);

}).call(this);

//# sourceMappingURL=portefolio.js.map
